version: "3"
services:
  db:
    build: .
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: hello-prisma
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
